DROP SCHEMA PUBLIC CASCADE

CREATE TABLE Blocky (
DKP varchar(255) NOT NULL, 
blocek_ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
datum timestamp,
time_inserted timestamp,
time_makro_generated timestamp,
registrator varchar(255),
suma decimal(5,2), 
pocet integer, 
PRIMARY KEY (blocek_ID));

CREATE TABLE predajne ( 
predajca_ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
dkp varchar(255) NOT NULL, 
meno varchar(255) NOT NULL, 
PRIMARY KEY (predajca_ID));

CREATE TABLE Loginy ( 
login_ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
meno varchar(255) NOT NULL, 
heslo varchar(255) NOT NULL, 
PRIMARY KEY (login_ID));

insert into loginy values(1, '','')
insert into loginy values(2, '','')
insert into loginy values(3, '','')

CREATE TABLE register_log ( log_ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
blocek_ID integer, 
login1 varchar(255) NOT NULL, 
login2 varchar(255) NOT NULL,
login3 varchar(255) NOT NULL, 
status1 varchar(1000) NOT NULL, 
status2 varchar(1000) NOT NULL,
status3 varchar(1000) NOT NULL,
PRIMARY KEY (log_ID));

