/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.blockova;

/**
 *
 * @author Janco1
 */
public class KalkulackaZarobku extends javax.swing.JFrame {

    double pocetRegistrovanych = 3000000;
    double rychlost = 15;
    private double pocetSpracovanychBlockovZaHodinu;
    private double pravdepodobnostVyhryPrvaSanca;
    double[] vyhry = {10000, 3000, 2500, 2000, 1000, 500, 400, 300, 200, 100};
    double cenaBlockaPrvaSanca = 0;
    private double blockyVDruhejSanci;
    private double cenaBlockaDruhaSanca;
    private double hodnota10000registracii;
    private double pocetRegistrovanychDruhaSanca;
    private double pravdepodobnostVyhryDruhaSanca;
    private double cenaRegistracie;
    private double registraciiZaHodinu;
    private double hodinovaMzda;

    /**
     * Creates new form KalkulackaZarobku
     */
    public KalkulackaZarobku() {
        initComponents();
        pocetRegistrovanychTextField.setText(Double.toString(pocetRegistrovanych));
        rychlostZadavaniaUdajovNaBlockuTextField.setText(Double.toString(rychlost));
                eurZa1000BlockovTextField.setText(Double.toString(7));
        hodinNaZrebovanieTextField.setText(Double.toString(80));
        vypocitajMzduButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rychlostZadavaniaUdajovNaBlockuTextField = new javax.swing.JTextField();
        pocetRegistrovanychTextField = new javax.swing.JTextField();
        vypocitajMzduButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cena3000RegistraciiLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registraciiZaHodinuLabel = new javax.swing.JLabel();
        hodinovaMzdaLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        celkovaHodnota10000Label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pocetSpracovanychBlockovZaHodinuLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hodin3333Label = new javax.swing.JLabel();
        za1000EurKupimLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        za1000EurKupeneHodnotaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pravdepodobnostVyhryPrvaSancaLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pravdepodobnostVyhryPrvaSanca10000Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cenaPrvaSancaLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cenaPrvaSanca10000Label = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pocetRegistraciiPrvaSancaLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pravdepodobnostVyhryDruhaSancaLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cenaDruhaSancaLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cenaDruhaSanca10000Label1 = new javax.swing.JLabel();
        pocetRegistraciiDruhaSancaLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pravdepodobnostVyhryDruhaSanca10000Label = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cenaRegistracieLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hodinNaZrebovanieTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pocetRegistraciiZaHodinLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        eurZa1000BlockovTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        kolkoTrebaKupitBlockovLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        kolkoZaNeZaplatimLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kolkoZaNeZarobimLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rychlost zadavania udajov na blocku:");

        jLabel2.setText("Pocet registrovanych blockov:");

        jLabel3.setText("Hodinova mzda:");

        rychlostZadavaniaUdajovNaBlockuTextField.setText("5");

        pocetRegistrovanychTextField.setText("4000000");
        pocetRegistrovanychTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocetRegistrovanychTextFieldActionPerformed(evt);
            }
        });

        vypocitajMzduButton.setText("Vypocitaj mzdu");
        vypocitajMzduButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypocitajMzduButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("cena 1000 papierovych blockov(3000 registracii): ");

        cena3000RegistraciiLabel.setText("cena");

        jLabel8.setText("registracii  za hodinu:");

        registraciiZaHodinuLabel.setText("jLabel9");

        hodinovaMzdaLabel.setText("jLabel12");

        jLabel12.setText("prva+druha sanca");

        jLabel14.setText("celkova hodnota 10 000 registracii:");

        celkovaHodnota10000Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        celkovaHodnota10000Label.setText("cena");

        jLabel15.setText("pocet spracovanych blockov za hodinu:");

        pocetSpracovanychBlockovZaHodinuLabel.setText("jLabel16");

        jLabel16.setText("- 14 eur za captcha (72-14= 58)");

        jLabel17.setText("za 1000 eur si kupim (7eur za 1000 blockov):");

        jLabel19.setText("kolko hodin je 10 000 registracii (3333 blockov): ");

        hodin3333Label.setText("jLabel20");

        za1000EurKupimLabel.setText("jLabel22");

        jLabel22.setText("za 1000 eur kupene blocky/registracie maju hodnotu:");

        za1000EurKupeneHodnotaLabel.setText("jLabel23");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Prvá šanca"));

        jLabel9.setText("pravdepodobnost vyhry (1 registracia):");

        pravdepodobnostVyhryPrvaSancaLabel.setText("jLabel10");

        jLabel10.setText("pravdepodobnost vyhry (10 000 registracii):");

        pravdepodobnostVyhryPrvaSanca10000Label.setText("jLabel10");

        jLabel7.setText("cena 1 registracie v prvej sanci: ");

        cenaPrvaSancaLabel.setText("cena");

        jLabel11.setText("cena 10 000 registracii v prvej sanci: ");

        cenaPrvaSanca10000Label.setText("cena");

        jLabel24.setText("Počet registrácií v hre: ");

        pocetRegistraciiPrvaSancaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pocetRegistraciiPrvaSancaLabel.setText("jLabel25");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pravdepodobnostVyhryPrvaSancaLabel)
                            .addComponent(pravdepodobnostVyhryPrvaSanca10000Label)
                            .addComponent(pocetRegistraciiPrvaSancaLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cenaPrvaSancaLabel)
                            .addComponent(cenaPrvaSanca10000Label))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pocetRegistraciiPrvaSancaLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pravdepodobnostVyhryPrvaSancaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pravdepodobnostVyhryPrvaSanca10000Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cenaPrvaSancaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cenaPrvaSanca10000Label))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Druhá šanca"));

        jLabel23.setText("pravdepodobnost vyhry (1 registracia):");

        pravdepodobnostVyhryDruhaSancaLabel.setText("jLabel10");

        jLabel18.setText("cena 1 registracie v druhej sanci: ");

        cenaDruhaSancaLabel.setText("cena");

        jLabel13.setText("cena 10 000 registracii v druhej sanci: ");

        cenaDruhaSanca10000Label1.setText("cena");

        pocetRegistraciiDruhaSancaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pocetRegistraciiDruhaSancaLabel.setText("jLabel25");

        jLabel25.setText("Počet registrácií v hre: ");

        pravdepodobnostVyhryDruhaSanca10000Label.setText("jLabel10");

        jLabel26.setText("pravdepodobnost vyhry (10 000 registracii):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(pocetRegistraciiDruhaSancaLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cenaDruhaSancaLabel)
                            .addComponent(pravdepodobnostVyhryDruhaSanca10000Label)
                            .addComponent(cenaDruhaSanca10000Label1)
                            .addComponent(pravdepodobnostVyhryDruhaSancaLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pocetRegistraciiDruhaSancaLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pravdepodobnostVyhryDruhaSancaLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(pravdepodobnostVyhryDruhaSanca10000Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cenaDruhaSancaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cenaDruhaSanca10000Label1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Cena 1 registracie:");

        cenaRegistracieLabel.setText("jLabel27");

        jLabel6.setText("Kolko hodin na jedno zrebovanie registrovanim:");

        hodinNaZrebovanieTextField.setText("jTextField1");

        jLabel20.setText("Kolko je z toho registracii:");

        pocetRegistraciiZaHodinLabel.setText("jLabel21");

        jLabel21.setText("Kolko eur za 1000 blockov:");

        eurZa1000BlockovTextField.setText("jTextField1");

        jLabel27.setText("Kolko treba kupit blockov:");

        kolkoTrebaKupitBlockovLabel.setText("jLabel28");

        jLabel28.setText("kolko za ne zaplatim:");

        kolkoZaNeZaplatimLabel.setText("jLabel29");

        jLabel29.setText("kolko za ne zarobim:");

        kolkoZaNeZarobimLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kolkoZaNeZarobimLabel.setText("jLabel30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pocetRegistrovanychTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(vypocitajMzduButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celkovaHodnota10000Label)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cena3000RegistraciiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)
                        .addGap(31, 31, 31)
                        .addComponent(hodin3333Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(rychlostZadavaniaUdajovNaBlockuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel17)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hodinovaMzdaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(registraciiZaHodinuLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cenaRegistracieLabel)
                                            .addComponent(pocetSpracovanychBlockovZaHodinuLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kolkoTrebaKupitBlockovLabel)
                    .addComponent(za1000EurKupimLabel)
                    .addComponent(za1000EurKupeneHodnotaLabel)
                    .addComponent(hodinNaZrebovanieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocetRegistraciiZaHodinLabel)
                    .addComponent(eurZa1000BlockovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolkoZaNeZaplatimLabel)
                    .addComponent(kolkoZaNeZarobimLabel))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pocetRegistrovanychTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(celkovaHodnota10000Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cena3000RegistraciiLabel)
                    .addComponent(jLabel12))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(rychlostZadavaniaUdajovNaBlockuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(za1000EurKupimLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(za1000EurKupeneHodnotaLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(pocetSpracovanychBlockovZaHodinuLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(eurZa1000BlockovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cenaRegistracieLabel)
                        .addComponent(jLabel6)
                        .addComponent(hodinNaZrebovanieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(registraciiZaHodinuLabel)
                    .addComponent(jLabel20)
                    .addComponent(pocetRegistraciiZaHodinLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hodinovaMzdaLabel)
                    .addComponent(jLabel27)
                    .addComponent(kolkoTrebaKupitBlockovLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(hodin3333Label)
                    .addComponent(jLabel28)
                    .addComponent(kolkoZaNeZaplatimLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(kolkoZaNeZarobimLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vypocitajMzduButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypocitajMzduButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypocitajMzduButtonActionPerformed
        pocetRegistrovanych = Double.parseDouble(pocetRegistrovanychTextField.getText());

// PRVA SANCA
        pocetRegistraciiPrvaSancaLabel.setText(Double.toString(pocetRegistrovanych));
        pravdepodobnostVyhryPrvaSanca = 1 / pocetRegistrovanych;
        pravdepodobnostVyhryPrvaSancaLabel.setText(Double.toHexString(pravdepodobnostVyhryPrvaSanca));
        pravdepodobnostVyhryPrvaSanca10000Label.setText(Double.toString(pravdepodobnostVyhryPrvaSanca * 10000));
        cenaBlockaPrvaSanca = 0;
        for (int i = 0; i < vyhry.length; i++) {
            cenaBlockaPrvaSanca += pravdepodobnostVyhryPrvaSanca * vyhry[i];
        }
        cenaPrvaSancaLabel.setText(Double.toString(cenaBlockaPrvaSanca));
        cenaPrvaSanca10000Label.setText(Double.toString(cenaBlockaPrvaSanca * 10000));

        //DRUHA SANCA
        pocetRegistrovanychDruhaSanca = pocetRegistrovanych / 4;
        pocetRegistraciiDruhaSancaLabel.setText(Double.toString(pocetRegistrovanychDruhaSanca));
        pravdepodobnostVyhryDruhaSanca = 1 / pocetRegistrovanychDruhaSanca;
        pravdepodobnostVyhryDruhaSancaLabel.setText(Double.toString(pravdepodobnostVyhryDruhaSanca));
        pravdepodobnostVyhryDruhaSanca10000Label.setText(Double.toString(pravdepodobnostVyhryDruhaSanca * 10000));
        cenaBlockaDruhaSanca = pravdepodobnostVyhryDruhaSanca * 5000;
        cenaDruhaSancaLabel.setText(Double.toString(cenaBlockaDruhaSanca));
        cenaDruhaSanca10000Label1.setText(Double.toString(cenaBlockaDruhaSanca * 10000));

        hodnota10000registracii = cenaBlockaPrvaSanca * 10000 + cenaBlockaDruhaSanca * 10000 - 14;
        celkovaHodnota10000Label.setText(Double.toString(hodnota10000registracii));
        cena3000RegistraciiLabel.setText(Double.toString(hodnota10000registracii / 3.33)); //prva + druha sanca     

//rychlost = Double.parseDouble(rychlostRegistracieTextField.getText());
        rychlost=Double.parseDouble(rychlostZadavaniaUdajovNaBlockuTextField.getText());
        pocetSpracovanychBlockovZaHodinu = 3600 / rychlost;
        pocetSpracovanychBlockovZaHodinuLabel.setText(Double.toString(pocetSpracovanychBlockovZaHodinu));
        cenaRegistracie = hodnota10000registracii / 10000;
        cenaRegistracieLabel.setText(Double.toString(cenaRegistracie));
        registraciiZaHodinu = pocetSpracovanychBlockovZaHodinu * 3;
        registraciiZaHodinuLabel.setText(Double.toString(registraciiZaHodinu));
        hodinovaMzda = registraciiZaHodinu * cenaRegistracie;
        hodinovaMzdaLabel.setText(Double.toString(hodinovaMzda));

        double hodin10000Registracii = 10000 / registraciiZaHodinu;
        hodin3333Label.setText(Double.toString(hodin10000Registracii));

        double eurZa1000Blockov=Double.parseDouble(eurZa1000BlockovTextField.getText());
        double za1000eurRegistracii = (1000 / eurZa1000Blockov) * 3000;
        za1000EurKupimLabel.setText(Double.toString(za1000eurRegistracii) + " registracii");
        za1000EurKupeneHodnotaLabel.setText(Double.toString((za1000eurRegistracii / 10000) * hodnota10000registracii));
        

        
        double hodinNaJednoZrebovanieVenujem=Double.parseDouble(hodinNaZrebovanieTextField.getText());
        double kolkoJeRegistracii=hodinNaJednoZrebovanieVenujem/hodin10000Registracii*10000;
        pocetRegistraciiZaHodinLabel.setText(Double.toString(kolkoJeRegistracii));
        double kolkoTrebaKupitBlockov=kolkoJeRegistracii/3;
        kolkoTrebaKupitBlockovLabel.setText(Double.toString(kolkoTrebaKupitBlockov));
        double kolkoZaNeZaplatim=(kolkoTrebaKupitBlockov/1000)*eurZa1000Blockov;
        kolkoZaNeZaplatimLabel.setText(Double.toString(kolkoZaNeZaplatim));
        double kolkoZaNeZarobim=kolkoJeRegistracii*cenaRegistracie;
        kolkoZaNeZarobimLabel.setText(Double.toString(kolkoZaNeZarobim));
    }//GEN-LAST:event_vypocitajMzduButtonActionPerformed

    private void pocetRegistrovanychTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocetRegistrovanychTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocetRegistrovanychTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulackaZarobku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulackaZarobku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulackaZarobku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulackaZarobku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulackaZarobku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celkovaHodnota10000Label;
    private javax.swing.JLabel cena3000RegistraciiLabel;
    private javax.swing.JLabel cenaDruhaSanca10000Label1;
    private javax.swing.JLabel cenaDruhaSancaLabel;
    private javax.swing.JLabel cenaPrvaSanca10000Label;
    private javax.swing.JLabel cenaPrvaSancaLabel;
    private javax.swing.JLabel cenaRegistracieLabel;
    private javax.swing.JTextField eurZa1000BlockovTextField;
    private javax.swing.JLabel hodin3333Label;
    private javax.swing.JTextField hodinNaZrebovanieTextField;
    private javax.swing.JLabel hodinovaMzdaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kolkoTrebaKupitBlockovLabel;
    private javax.swing.JLabel kolkoZaNeZaplatimLabel;
    private javax.swing.JLabel kolkoZaNeZarobimLabel;
    private javax.swing.JLabel pocetRegistraciiDruhaSancaLabel;
    private javax.swing.JLabel pocetRegistraciiPrvaSancaLabel;
    private javax.swing.JLabel pocetRegistraciiZaHodinLabel;
    private javax.swing.JTextField pocetRegistrovanychTextField;
    private javax.swing.JLabel pocetSpracovanychBlockovZaHodinuLabel;
    private javax.swing.JLabel pravdepodobnostVyhryDruhaSanca10000Label;
    private javax.swing.JLabel pravdepodobnostVyhryDruhaSancaLabel;
    private javax.swing.JLabel pravdepodobnostVyhryPrvaSanca10000Label;
    private javax.swing.JLabel pravdepodobnostVyhryPrvaSancaLabel;
    private javax.swing.JLabel registraciiZaHodinuLabel;
    private javax.swing.JTextField rychlostZadavaniaUdajovNaBlockuTextField;
    private javax.swing.JButton vypocitajMzduButton;
    private javax.swing.JLabel za1000EurKupeneHodnotaLabel;
    private javax.swing.JLabel za1000EurKupimLabel;
    // End of variables declaration//GEN-END:variables
}
